In [3]:
import numpy

In [4]:
numpy.__version__

'1.16.2'

In [5]:
import numpy as np

python list 的特点

In [6]:
l=[i for i in range(10)]

In [7]:
import array

arr 中只能存特定类型是数据

ｎumpy.array

In [8]:
nparr=np.array([i for i in range(10)])

In [9]:
nparr.dtype

dtype('int64')

## 特殊的创建方式

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.zeros(shape=(3,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [13]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.full(shape=(3,5),fill_value=666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [15]:
np.full(shape=(3,5),fill_value=666.0)

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

In [16]:
[i for i in range(0,20,2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [17]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
np.arange(0,2,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

linspace(start,end,pointNums)

In [19]:
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

random

In [20]:
np.random.randint(0,10)

1

In [21]:
np.random.randint(0,10,10)

array([2, 5, 1, 4, 6, 6, 2, 5, 4, 9])

In [22]:
np.random.randint(0,1,size=10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
np.random.seed(666) #随机种子

In [25]:
np.random.random(10)

array([0.70043712, 0.84418664, 0.67651434, 0.72785806, 0.95145796,
       0.0127032 , 0.4135877 , 0.04881279, 0.09992856, 0.50806631])

In [29]:
np.random.random((3,5))

array([[0.20024754, 0.74415417, 0.192892  , 0.70084475, 0.29322811],
       [0.77447945, 0.00510884, 0.11285765, 0.11095367, 0.24766823],
       [0.0232363 , 0.72732115, 0.34003494, 0.19750316, 0.90917959]])

In [30]:
np.random.normal()# 正态分布

0.028016723832884196

In [31]:
np.random.normal(10,100) #均值为10，方差100

50.85571939822264

In [32]:
np.random.normal?

In [1]:
# x.ndim,x.shape,x.size 
# 访问二维数组元素X[x,y]
#　切片X[:2,:3]　前两行，三列.dou
# 切片得到的子矩阵是类似引用的机制
# subX=X[:2,:3].copy() 这样得到的就是一个新的子矩阵
# reshape(n,-1) 只指定一个维度

## 合并和分割

## 运算

In [2]:
# 2*L 数乘
# L+1,L-1,L/2 浮点除法，L//2　整数除法　还有其他的也类似
# 矩阵运算　＋，－，*,/
# 矩阵乘法A.dot(B)
# A.T 转置
# 向量和矩阵可以做加法，或者用vstack进行堆叠
# 矩阵求逆　np.linalg.inv(A)
# 矩阵求伪逆　np.linalg.pinv(A)# 


## 聚合操作

In [3]:
# np.sum,np.min,np.max,prod 乘积，mean,median,percentile求百分位,var,std,

## 索引

In [8]:
# argmin 返回最小值的索引值，argsort,X.sort,np.sort(),这两个排序不一样
# np.partition()


# Fancy indexing